### ISSUE TITLE
Почему нужный для markdown символы по Shift+AltGr в не по AltGr

### ISSUE THREAD

**Issue by ivangretsky** [Atarity/Strata#3]
Добрый день!

Очень интересный проект. Наконец решился поставить и попробовать. И как раз, прежде всего, для markdown. Мне показалост странным, что наиболее нужные для этой разметки символы (`#`, `>`) спрятаны за Shift+AltGr в не за AltGr. В то время как `[` и backtick за AltGr.

И, судя по коммитам, так было не всегда. Может быть, имеет смысл все по AltGr вызывать?

**Comment by Atarity** [comment]
@ivangretsky Когда я только начинал проектировать эту раскладку основные правила были такие (без исключений не обошлось):
- Визуально похожие символы должны быть сгруппированы на одной клавише. 
- Если в дефолтовой английской раскладке важный символ (например `{` или `<`) доступен с shift, то нужно продублировать его в русской и английской Страте через AltGr+Shift. Это сделано для того, чтобы вводить их в любом языке одинаковым образом не думая какая раскладка Страты включена прямо сейчас. Скорее это был просто вопрос преемственности раскладок.

На удобство ввода это не влияет. Во всяком случае мне так казалось уже после 2-3 недель использования. Я не старался делить символы на часто используемые в `.md` и все остальные. Поэтому в раскладке не было правила «всё, что используется в маркдауне ставим исключительно на AltGr».

Но! Всё это легко исправляется и вы можете нарулить нужный вам паттерн. 
- Или, если используете Мак, вообще сделать какой-то крохотный патч за 10 мин для Karabiner, чтобы поменять или продублировать неудобные клавиши.
- Или, если доступный Маркдаун это единственная цель и до остальных символов нет большого дела, можно вообще освободить какую-то условно-ненужную кнопку типа Caps Lock и использовать её в качестве эксклюзивного Маркдаун-модификатора. Это мне тоже кажется логичнее делать через Карабинер и не городить отдельную раскладку для такого. Я даже думаю, что для Карабинера **уже** есть такие патчи.

**Comment by ivangretsky** [comment]
Понял. Я на Винде) Попробую AHK
