### ISSUE TITLE
Win 10 не показывает русскую раскладку

### ISSUE THREAD

**Issue by schmalhausen** [Atarity/Strata#4]
Windows 10. Установил русскую раскладку. Добавил её в список раскладок для русского языка. При переключении языка и раскладки Русская (маркдаун) не показывается и не выбирается.
Поставил Русская (маркдаун) в качестве основной: теперь раскладка выбирается, но в индикаторе всегда висит eng.
Удалил основную русскую раскладку: теперь индикатор языка вообще пропал.

**Comment by schmalhausen** [comment]
Решилось перезагрузкой

**Comment by Atarity** [comment]
Рад, что всё решилось. Иногда после установки раскладки на Винде случаются конфликты с Punto Switcher. Обычно раньше они решались одноразовой перезагрузкой самого Пунто, но что происходит в Win сейчас я, к сожалению, не знаю.
